name: workforce_app
description: Multi-tenant workforce management (Flutter)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_riverpod: ^2.5.1
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.1.5
  flutter_secure_storage: ^9.2.4
  table_calendar: ^3.0.9
  flutter_chat_ui: ^2.9.0
  flutter_svg: ^2.0.10
  provider: ^6.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^3.2.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

flutter_native_splash:
  color: "#ffffff"
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
